### ISSUE TITLE
Text resize so it doesn't feel so big and playful

### ISSUE THREAD

**Issue by liwentran** [skynth/AKPSI-Rho-Psi#2]

**Comment by skynth** [comment]
- increase padding, smaller text, but mobile needs bigger

**Comment by liwentran** [comment]
<img width="1512" alt="Screenshot 2023-01-30 at 2 36 30 AM" src="https://user-images.githubusercontent.com/89868439/215415471-bbc3a57f-cfaf-4023-a517-05cba60e6120.png">
![Screenshot 2023-01-30 at 2 36 30 AM 2](https://user-images.githubusercontent.com/89868439/215415478-6d3c4a19-4bb0-4f9e-97ec-cf85d0a2ddd4.png)

This size is unluckily ugly
